feature/authentication
far1dghaderi/medcome pull request #17
Opened 2022-05-17 13:54 UTC by far1dghaderi

استفاده از passport local و jwt برای احراز هویت کاربران و استفاده از متغیرهای env برای کانفیگ کردن برنامه

2022-05-17 14:40 UTC, alisalemmi requested changes
گارد های jwt و role را با هم ادغام کن

2022-05-17 14:40 UTC, alisalemmi commented on .gitignore
> +config.env
به جای یک فایل env پوشه env. را ignore کن

2022-05-17 14:40 UTC, alisalemmi commented on example.config.env
> +JWT_EXPIRES_IN =
نیازی به مثال نیست!

2022-05-17 14:40 UTC, alisalemmi commented on package.json
> +    "cookie-parser": "^1.4.6",
نباید dev dependency باشد

2022-05-17 14:40 UTC, alisalemmi commented on src/user/user.controller.ts
> +  @UseGuards(JwtAuthGuard)
هر دو تا decorator زیر را با هم ادغام کن

```
@UseGuards(JwtAuthGuard)
@MatchRoles('admin', 'user')
  ```

2022-05-17 14:40 UTC, alisalemmi commented on src/auth/passport/jwt/jwt.strategy.ts
> +  async validate(payload: any) {
به جای any از `JwtPayload` استفاده کن

2022-05-17 14:40 UTC, alisalemmi commented on src/auth/passport/jwt/jwt.strategy.ts
> +    return { userId: payload.sub, email: payload.email };
باید درست بودن id و revoke نشدن توکن در این قسمت بررسی شود.
اطلاعات کاربر باید برگردانده شود.

2022-05-17 14:40 UTC, alisalemmi commented on src/auth/auth.service.ts
> +    if (email && user.password === password) {
email یا user?

2022-05-19 10:16 UTC, far1dghaderi commented
> گارد های jwt و role را با هم ادغام کن

چون این دو گارد هر کدام برای کار متفاوتی استفاده می‌شوند به‌ نظر من درست نیست که با هم ادغام بشن و برای همین این مورد رو اگه اجازه بدید رد می‌کنم

2022-05-19 14:29 UTC, merged